### ISSUE TITLE
Students are not taught how to define default arguments in the lessons leading up to this lab.

### ISSUE THREAD

**Issue by ddeleon267** [learn-co-curriculum/programming-univbasics-3-ruby-method-arguments-lab#3]
Students are expected to define default arguments for this lab but are not taught how to do so in the lessons preceding it ("Defining Methods" and "Methods and Arguments"). 

I often have to refer students to the following lesson, which does have examples:
https://learn.co/lessons/methods-default-arguments

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

It turns out there was a duplicate repo of "Methods and Arguments" without the default arguments section. We have updated the material in that lesson and believe your issue to have been resolved. 

If you do not believe that this issue has been addressed, please re-open this issue. 💙
