### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by Joey0719** [learn-co-curriculum/programming-univbasics-3-ruby-method-arguments-lab#4]
Is it really necessary for student to submit pull request when he/she doesn't really need too..

**Comment by sgharms** [comment]
As far as I can tell, this lab doesn't ask anyone to submit a pull request. This is likely a question best handled by "Ask A Question" where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) can help you figure it out.

If the issue is in the text here or the test suite, please re-open and we will address.
